version: '3.1'
services:
  db-backup:  
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: db-backup
    links:
     - strapidb:strapidb
    volumes:
      - /db_backup:/backup